application: 
  test: 7

info:
  component: Chat OGW
  version: '@project.version@'

server:
  port: 8808
logging:
  level:
    org.springframework: debug

spring:
  cloud:
    bus:
      destination: engagement-configuration
      trace:
        enabled: true
